#!/usr/bin/env python3
"""Generate and verify a local flywheel sandbox flow.

The sandbox is intentionally file-based so it works before br/bv/Agent Mail are
installed. When those tools are present, this script records their availability
and the next command to run rather than pretending the integration is complete.
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SANDBOX = ROOT / "sandbox" / "sample-flow"
LOCAL_BIN = str(Path.home() / ".local" / "bin")


def write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def tool_status(command: str) -> dict[str, str | bool]:
    found = shutil.which(command, path=f"{LOCAL_BIN}:{__import__('os').environ.get('PATH', '')}")
    result: dict[str, str | bool] = {"available": bool(found)}
    if found:
        result["path"] = found
        try:
            completed = subprocess.run(
                [command, "--version"],
                check=False,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
                timeout=5,
            )
            result["version"] = completed.stdout.strip()
        except Exception as exc:  # pragma: no cover - diagnostic only
            result["version"] = f"version check failed: {exc}"
    return result


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--clean", action="store_true", help="replace existing sandbox/sample-flow")
    args = parser.parse_args()

    if args.clean and SANDBOX.exists():
        shutil.rmtree(SANDBOX)
    SANDBOX.mkdir(parents=True, exist_ok=True)

    now = datetime.now().strftime("%Y-%m-%d %H:%M")

    write(
        SANDBOX / "docs" / "specs" / "sample-course-profile.spec.md",
        f"""
        # Feature Spec: Sample Course Profile Prompt Flow

        Status: Sandbox
        Date: {now}

        ## Goal

        Demonstrate that the internal flywheel can turn a rough study-agent idea into a spec, task bead, worker profile, worker brief, decision request, review report, workflow improvement, and session-end handoff.

        ## In Scope

        - Define a sample course-aware prompt profile task.
        - Create one task bead with a worker-profile decision.
        - Create one reusable worker profile.
        - Create one worker brief.
        - Create one decision request.
        - Create one review report and workflow improvement.

        ## Out of Scope

        - Implement the future study-agent product.
        - Call an LLM provider.
        - Install external flywheel tools.

        ## Acceptance Criteria

        - [ ] Every artifact in this sandbox links to the same bead ID.
        - [ ] The bead has a worker-profile reuse/create decision.
        - [ ] The decision request has severity, options, recommendation, and default behavior.
        - [ ] The session-end checklist invokes workflow optimization.
        """,
    )

    write(
        SANDBOX / "docs" / "tasks" / "fw-sandbox-001.md",
        """
        # Task Bead: fw-sandbox-001 Create sample prompt profile worker flow

        Status: ready
        Priority: P2
        Type: task
        Depends On: none

        ## Worker Profile

        create `prompt-profile-worker`

        Rationale:

        Prompt profile work is likely to recur across course-aware tutoring, flashcard generation, quiz generation, and explanation tasks.

        ## Context

        This task exercises the flywheel's artifact ladder without changing product code.

        ## What To Do

        - Use a profile specialized for prompt metadata and eval fixture expectations.
        - Produce a worker brief constrained to sandbox artifacts.

        ## Likely Files / Packages

        - `sandbox/sample-flow/docs/**`: generated sandbox artifacts only.

        ## Acceptance Criteria

        - [ ] A reusable worker profile exists.
        - [ ] A worker brief references this bead and profile.
        - [ ] A decision request models a realistic blocker.

        ## Verification

        - `scripts/run-sandbox-flow.py --clean`: regenerates this flow.

        ## Out Of Scope

        - Editing product code.

        ## Notes / Handoff

        - Generated by sandbox flow.
        """,
    )

    write(
        SANDBOX / "docs" / "worker-profiles" / "prompt-profile-worker.md",
        """
        # Worker Profile: prompt-profile-worker

        ## Reuse Trigger

        Use this worker when a bead changes course-aware prompt policy, prompt metadata, output schemas, or eval fixtures.

        ## Mandate

        Produce prompt-system artifacts that are versioned, testable, and grounded in the current spec.

        ## Scope

        In scope:

        - Prompt metadata.
        - Course profile policy constraints.
        - Eval fixture outlines.

        Out of scope:

        - Provider-specific SDK calls.
        - Product UI implementation.

        ## Required Context

        Read first:

        - `docs/specs/sample-course-profile.spec.md`
        - `docs/tasks/fw-sandbox-001.md`

        Current-doc research:

        - not needed for this sandbox.

        ## Allowed Files

        May edit:

        - `sandbox/sample-flow/docs/**`

        May inspect:

        - `study-agent-devkit/templates/**`

        Do not edit:

        - product code outside `sandbox/sample-flow/`

        ## Forbidden Decisions

        Stop and report back before deciding:

        - canonical prompt registry schema;
        - provider choice;
        - persistent data model.

        ## Quality Gates

        - Every prompt behavior change has an eval note.
        - Every generated study object mentions provenance expectations.
        - Scope remains sandbox-only.

        ## Verification

        Run:

        ```bash
        scripts/run-sandbox-flow.py --clean
        ```

        ## Report Format

        Return:

        - files changed;
        - verification results;
        - constraints followed;
        - unresolved questions;
        - recommended next worker or review step.
        """,
    )

    write(
        SANDBOX / "docs" / "worker-briefs" / "fw-sandbox-001.prompt-profile-worker.md",
        """
        # Worker Brief: fw-sandbox-001

        ## Assignment

        Use `prompt-profile-worker` to draft prompt-profile sandbox artifacts for `fw-sandbox-001`.

        ## Read First

        - `docs/specs/sample-course-profile.spec.md`
        - `docs/tasks/fw-sandbox-001.md`
        - `docs/worker-profiles/prompt-profile-worker.md`

        ## Scope

        You may change:

        - `sandbox/sample-flow/docs/**`

        Do not change:

        - files outside `sandbox/sample-flow/`

        ## Requirements

        - Keep the task linked to `fw-sandbox-001`.
        - Create a decision request instead of asking an unstructured chat question.

        ## Verification

        Run:

        ```bash
        scripts/run-sandbox-flow.py --clean
        ```

        ## Report Back

        Return changed files, verification result, constraints followed, unresolved questions, and next step.
        """,
    )

    write(
        SANDBOX / "docs" / "decision-requests" / "fw-sandbox-001-course-profile-source.md",
        """
        # Decision Request: fw-sandbox-001-course-profile-source

        Status: Open
        Bead: fw-sandbox-001
        Agent: prompt-profile-worker

        ## Severity

        important

        ## Decision Type

        product

        ## Question

        Should course profiles start as built-in presets only, or should user-authored profiles be allowed in the first implementation?

        ## Context

        User-authored profiles increase flexibility but require validation, persistence, and abuse-resistant prompt composition.

        ## Options

        1. `presets-only`: Built-in profiles only.
           - Consequence: faster and safer first implementation.

        2. `user-authored`: Allow users to create profiles.
           - Consequence: more powerful but requires validation and UI.

        ## Recommendation

        Recommended option: `presets-only`

        Reason:

        It keeps the first implementation testable while leaving room for later user-authored profiles.

        ## Default If Unanswered

        Use `presets-only` for reversible planning artifacts. Do not implement persistence until confirmed.

        ## Links

        - `docs/tasks/fw-sandbox-001.md`

        ## Resolution

        Answered by:
        Answered at:
        Decision:
        Follow-up beads:
        """,
    )

    write(
        SANDBOX / "docs" / "reviews" / "fw-sandbox-001.review.md",
        """
        # Review Report: fw-sandbox-001

        ## Findings

        - No blocking findings in sandbox artifact flow.

        ## Required Fixes

        - None.

        ## Test Gaps

        - External `br`/`bv`/Agent Mail integration is not proven by this file-only sandbox.

        ## Architecture Notes

        - Worker profile creation is represented as an explicit bead decision.

        ## Prompt / Eval Notes

        - Prompt profile work should require eval fixture notes in real product code.

        ## Verdict

        Approved
        """,
    )

    write(
        SANDBOX / "docs" / "workflow-improvements" / "fw-sandbox-001.workflow-improvement.md",
        """
        # Workflow Improvement: Sandbox tool integration gap

        Status: Proposed
        Source: fw-sandbox-001

        ## Problem

        The file-based sandbox proves artifact shape but not live `br`/`bv`/Agent Mail integration.

        ## Evidence

        - The sandbox generates markdown artifacts only.

        ## Proposed Change

        Target:

        - `scripts/run-sandbox-flow.py`

        Change:

        Add a `--with-core-tools` mode after the tools are installed to create matching `br` issues and Agent Mail threads.

        ## Expected Benefit

        Proves the full coordination loop with real upstream tools.

        ## Risk / Cost

        Requires network/install setup and tool-specific command stability.

        ## Recommendation

        review-first

        ## Follow-Up Beads

        - `fw-002`: install and test `br`, `bv`, and Agent Mail.
        """,
    )

    write(
        SANDBOX / "docs" / "session-end" / "fw-sandbox-001.session-end.md",
        """
        # Session-End Checklist

        Session: fw-sandbox-001

        ## Work Completed

        - Generated a full file-based artifact ladder.

        ## Verification

        - `scripts/run-sandbox-flow.py --clean`: regenerated sandbox.

        ## Open Beads / Follow-Ups

        - `fw-002`: install and test `br`, `bv`, and Agent Mail.

        ## Decisions Made

        - Dynamic worker profiles are represented as bead-level decisions.

        ## Workflow Optimizer

        Checklist:

        - [x] Avoidable agent questions identified.
        - [x] Missing bead context or acceptance criteria identified.
        - [x] Worker profile gaps identified.
        - [x] AGENTS.md or skill updates proposed if useful.
        - [x] Quality gate gaps identified.
        - [x] Workflow improvements recorded with `templates/workflow-improvement.md` or explicitly marked unnecessary.

        ## Handoff

        Next step is proving the same flow with live `br`/`bv`/Agent Mail.
        """,
    )

    artifacts = sorted(str(p.relative_to(ROOT)) for p in SANDBOX.rglob("*.md"))
    required = [
        "docs/specs/sample-course-profile.spec.md",
        "docs/tasks/fw-sandbox-001.md",
        "docs/worker-profiles/prompt-profile-worker.md",
        "docs/worker-briefs/fw-sandbox-001.prompt-profile-worker.md",
        "docs/decision-requests/fw-sandbox-001-course-profile-source.md",
        "docs/reviews/fw-sandbox-001.review.md",
        "docs/workflow-improvements/fw-sandbox-001.workflow-improvement.md",
        "docs/session-end/fw-sandbox-001.session-end.md",
    ]

    missing = [item for item in required if not (SANDBOX / item).exists()]
    report = {
        "generated_at": now,
        "sandbox": str(SANDBOX.relative_to(ROOT)),
        "artifacts": artifacts,
        "missing": missing,
        "tools": {cmd: tool_status(cmd) for cmd in ["br", "bv", "mcp-agent-mail", "am"]},
        "next_step": "Install and test br/bv/Agent Mail, then add live-tool mode.",
    }
    write(SANDBOX / "run-report.json", json.dumps(report, indent=2, sort_keys=True))

    if missing:
        print(json.dumps(report, indent=2))
        return 1

    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
